use std::fs;
use std::path::{Path, PathBuf};

use time::OffsetDateTime;

use crate::api_spec::{ApiBody, ApiEndpoint, ApiField};
use crate::error::Result;
use crate::plan::Plan;
use crate::ui_spec::{BusinessRule, UiScreen, Workflow};

/// Writes the on-disk Plan Bundle. Primary documents:
///   - `PRD.md`                 the execution plan as readable markdown
///   - `API.md`                 backend API documentation
///   - `UI.md`                  UI architecture + business-logic analysis
///   - `CODING_AGENT_PROMPT.md` single-prompt handoff for one downstream coding agent
/// Machine-readable companions: `plan.json`, `tasks.json`, `confidence.json`,
/// `risks.md`, `sources/*.json`, `audit.log`.
#[derive(Debug)]
pub struct PlanBundleWriter<'a> {
    plan: &'a Plan,
}

impl<'a> PlanBundleWriter<'a> {
    #[must_use]
    pub fn new(plan: &'a Plan) -> Self {
        Self { plan }
    }

    pub fn write_to(&self, parent_dir: &Path) -> Result<PathBuf> {
        let stamp = self.plan.created_at;
        let dir_name = format!(
            "plan-{:04}{:02}{:02}-{:02}{:02}",
            stamp.year(),
            u8::from(stamp.month()),
            stamp.day(),
            stamp.hour(),
            stamp.minute()
        );
        let out = parent_dir.join(dir_name);
        fs::create_dir_all(&out)?;
        fs::create_dir_all(out.join("sources"))?;

        fs::write(out.join("PRD.md"), self.prd_md())?;
        fs::write(out.join("API.md"), self.api_md())?;
        fs::write(out.join("UI.md"), self.ui_md())?;
        fs::write(out.join("CODING_AGENT_PROMPT.md"), self.coding_agent_prompt())?;
        fs::write(out.join("risks.md"), self.risks_md())?;
        fs::write(out.join("tasks.json"), serde_json::to_string_pretty(&self.plan.tasks)?)?;
        fs::write(
            out.join("confidence.json"),
            serde_json::to_string_pretty(&self.plan.confidence)?,
        )?;
        fs::write(out.join("plan.json"), serde_json::to_string_pretty(self.plan)?)?;
        fs::write(
            out.join("audit.log"),
            format!(
                "{{\"event\":\"bundle_written\",\"plan_id\":\"{}\",\"at\":\"{}\"}}\n",
                self.plan.id,
                OffsetDateTime::now_utc()
            ),
        )?;

        for c in &self.plan.citations {
            let path = out.join("sources").join(format!("{}.json", c.id));
            fs::write(path, serde_json::to_string_pretty(c)?)?;
        }

        Ok(out)
    }

    fn prd_md(&self) -> String {
        let p = self.plan;
        let mut s = String::new();
        s.push_str("# Execution Plan (PRD)\n\n");
        s.push_str(&format!(
            "*Generated by Godsy on {} for request:*\n\n> {}\n\n",
            p.created_at, p.user_request
        ));

        s.push_str("## 1. Problem Statement\n\n");
        s.push_str(&format!("{}\n\n", p.problem.summary));

        s.push_str("### Success Criteria\n\n");
        for c in &p.problem.success_criteria {
            s.push_str(&format!("- {c}\n"));
        }
        if !p.problem.assumptions.is_empty() {
            s.push_str("\n### Assumptions\n\n");
            for a in &p.problem.assumptions {
                s.push_str(&format!("- {a}\n"));
            }
        }
        if !p.problem.clarifications.is_empty() {
            s.push_str("\n### Clarifications Captured\n\n");
            for c in &p.problem.clarifications {
                s.push_str(&format!("- {c}\n"));
            }
        }

        s.push_str("\n## 2. Architecture Overview\n\n");
        s.push_str(&format!("{}\n\n", p.architecture.overview));
        s.push_str("```mermaid\n");
        s.push_str(&p.architecture.mermaid_diagram);
        s.push_str("\n```\n\n");

        s.push_str("### Components\n\n");
        for c in &p.architecture.components {
            let deps =
                if c.depends_on.is_empty() { "—".to_string() } else { c.depends_on.join(", ") };
            s.push_str(&format!(
                "- **{}** (`{}`) — {} *(depends on: {})*\n",
                c.name, c.id, c.responsibility, deps
            ));
        }

        s.push_str("\n## 3. Stack Decision\n\n");
        s.push_str(&format!("- **Language**: {}\n", p.stack.language));
        s.push_str(&format!("- **Frameworks**: {}\n", p.stack.frameworks.join(", ")));
        s.push_str(&format!("- **Storage**: {}\n", p.stack.storage));
        s.push_str(&format!("- **Runtime target**: {}\n\n", p.stack.runtime_target));
        s.push_str(&format!("**Rationale**: {}\n\n", p.stack.rationale));
        if !p.stack.citation_ids.is_empty() {
            s.push_str("**Citations**: ");
            s.push_str(
                &p.stack
                    .citation_ids
                    .iter()
                    .map(|c| format!("`{c}`"))
                    .collect::<Vec<_>>()
                    .join(", "),
            );
            s.push_str("\n\n");
        }

        s.push_str("## 4. Data Model\n\n");
        for e in &p.data_model.entities {
            s.push_str(&format!("### `{}` — {}\n\n", e.id, e.name));
            s.push_str("| Field | Type | Required | Notes |\n|---|---|---|---|\n");
            for f in &e.fields {
                s.push_str(&format!(
                    "| `{}` | `{}` | {} | {} |\n",
                    f.name,
                    f.ty,
                    f.required,
                    f.notes.clone().unwrap_or_default()
                ));
            }
            s.push('\n');
        }

        s.push_str("## 5. Execution Tasks (ordered)\n\n");
        let mut tasks = p.tasks.clone();
        tasks.sort_by_key(|t| t.order);
        s.push_str("| # | ID | Goal | Complexity | Files | Depends on |\n");
        s.push_str("|---|----|------|------------|-------|------------|\n");
        for t in &tasks {
            let files = if t.files_touched.is_empty() {
                "—".to_string()
            } else {
                t.files_touched.join(", ")
            };
            let deps =
                if t.depends_on.is_empty() { "—".to_string() } else { t.depends_on.join(", ") };
            s.push_str(&format!(
                "| {} | `{}` | {} | {:?} | {} | {} |\n",
                t.order, t.id, t.goal, t.complexity, files, deps
            ));
        }

        s.push_str("\n### Acceptance Criteria per Task\n\n");
        for t in &tasks {
            s.push_str(&format!("**`{}` — {}**\n\n", t.id, t.goal));
            for ac in &t.acceptance_criteria {
                s.push_str(&format!("- {ac}\n"));
            }
            s.push('\n');
        }

        s.push_str("## 6. Confidence Report\n\n");
        s.push_str(&format!("Threshold: **{:.2}**\n\n", p.confidence.threshold));
        s.push_str("| Section | Score | Citations |\n|---|---|---|\n");
        for sec in &p.confidence.sections {
            let cites = if sec.citation_ids.is_empty() {
                "—".to_string()
            } else {
                sec.citation_ids.iter().map(|c| format!("`{c}`")).collect::<Vec<_>>().join(", ")
            };
            s.push_str(&format!("| {} | {:.2} | {} |\n", sec.section, sec.score, cites));
        }

        s.push_str("\n## 7. Companion Documents\n\n");
        s.push_str("- `API.md` — backend API documentation\n");
        s.push_str("- `UI.md` — UI architecture + business-logic analysis\n");
        s.push_str("- `CODING_AGENT_PROMPT.md` — paste into one coding agent to begin the build\n");
        s.push_str("- `risks.md` — risks and mitigations\n");
        s.push_str("- `tasks.json`, `confidence.json`, `plan.json` — machine-readable views\n");
        s.push_str("- `sources/` — cached citation payloads\n");
        s
    }

    fn api_md(&self) -> String {
        let api = &self.plan.api;
        let mut s = String::new();
        s.push_str("# Backend API Documentation\n\n");
        s.push_str(&format!(
            "**Base URL**: `{}`\n\n",
            if api.base_url.is_empty() { "(to be assigned at deploy time)" } else { &api.base_url }
        ));

        if let Some(auth) = &api.auth {
            s.push_str("## Authentication\n\n");
            s.push_str(&format!("- **Scheme**: `{:?}`\n", auth.scheme));
            s.push_str(&format!("- **Description**: {}\n\n", auth.description));
        } else {
            s.push_str("## Authentication\n\nNo authentication required for the MVP. Add an auth layer before any deployment touches sensitive data.\n\n");
        }

        if api.endpoints.is_empty() {
            s.push_str("\n*(No HTTP endpoints in this plan. The application is local-only or in-process.)*\n");
            return s;
        }

        s.push_str("## Endpoints\n\n");
        s.push_str("| Method | Path | Summary |\n|---|---|---|\n");
        for e in &api.endpoints {
            s.push_str(&format!("| `{}` | `{}` | {} |\n", e.method.as_str(), e.path, e.summary));
        }
        s.push('\n');

        for e in &api.endpoints {
            s.push_str(&Self::endpoint_md(e));
            s.push('\n');
        }
        s
    }

    fn endpoint_md(e: &ApiEndpoint) -> String {
        let mut s = String::new();
        s.push_str(&format!("### `{} {}` — {}\n\n", e.method.as_str(), e.path, e.summary));
        s.push_str(&format!("- **ID**: `{}`\n", e.id));
        s.push_str(&format!("- **Auth required**: {}\n", e.auth_required));
        if !e.entity_refs.is_empty() {
            s.push_str(&format!("- **Entities**: {}\n", e.entity_refs.join(", ")));
        }
        if !e.component_refs.is_empty() {
            s.push_str(&format!("- **Owning component**: {}\n", e.component_refs.join(", ")));
        }
        s.push('\n');

        if !e.path_params.is_empty() {
            s.push_str("**Path parameters**\n\n");
            s.push_str(&fields_table(&e.path_params));
            s.push('\n');
        }
        if !e.query_params.is_empty() {
            s.push_str("**Query parameters**\n\n");
            s.push_str(&fields_table(&e.query_params));
            s.push('\n');
        }
        if let Some(req) = &e.request_body {
            s.push_str(&body_md("Request body", req));
        }
        if let Some(resp) = &e.response_body {
            s.push_str(&body_md("Response body", resp));
        }
        if !e.statuses.is_empty() {
            s.push_str("**Status codes**\n\n");
            s.push_str("| Code | Description |\n|---|---|\n");
            for st in &e.statuses {
                s.push_str(&format!("| {} | {} |\n", st.code, st.description));
            }
            s.push('\n');
        }
        s
    }

    fn ui_md(&self) -> String {
        let ui = &self.plan.ui;
        let bl = &self.plan.business_logic;
        let mut s = String::new();
        s.push_str("# UI Architecture & Business Logic Analysis\n\n");

        s.push_str("## 1. Frontend Stack\n\n");
        s.push_str(&format!("- **Framework**: {}\n", ui.framework));
        s.push_str(&format!("- **State management**: {}\n", ui.state_management));
        if !ui.design_notes.is_empty() {
            s.push_str(&format!("\n**Design notes**: {}\n", ui.design_notes));
        }

        s.push_str("\n## 2. Screens\n\n");
        for sc in &ui.screens {
            s.push_str(&screen_md(sc));
        }

        if !ui.shared_components.is_empty() {
            s.push_str("## 3. Shared Components\n\n");
            for c in &ui.shared_components {
                s.push_str(&format!("### `{}` — {} ({})\n\n", c.id, c.name, c.kind));
                s.push_str(&format!("{}\n\n", c.responsibility));
                if !c.props.is_empty() {
                    s.push_str("| Prop | Type | Required |\n|---|---|---|\n");
                    for p in &c.props {
                        s.push_str(&format!("| `{}` | `{}` | {} |\n", p.name, p.ty, p.required));
                    }
                    s.push('\n');
                }
            }
        }

        s.push_str("## 4. Business Logic Analysis\n\n");
        if !bl.overview.is_empty() {
            s.push_str(&format!("{}\n\n", bl.overview));
        }

        if !bl.rules.is_empty() {
            s.push_str("### Business Rules\n\n");
            for r in &bl.rules {
                s.push_str(&rule_md(r));
            }
        }
        if !bl.workflows.is_empty() {
            s.push_str("### Workflows\n\n");
            for w in &bl.workflows {
                s.push_str(&workflow_md(w));
            }
        }
        s
    }

    fn risks_md(&self) -> String {
        let mut s = String::new();
        s.push_str("# Risks\n\n");
        if self.plan.risks.is_empty() {
            s.push_str("*No risks flagged.*\n");
            return s;
        }
        for r in &self.plan.risks {
            s.push_str(&format!(
                "## {} ({:?})\n\n{}\n\n**Mitigation**: {}\n\n",
                r.id, r.severity, r.description, r.mitigation
            ));
        }
        s
    }

    fn coding_agent_prompt(&self) -> String {
        let p = self.plan;
        let mut s = String::new();
        s.push_str("# Coding Agent Handoff Prompt\n\n");
        s.push_str(
            "You are a coding agent. Implement the project below in a single session, \
             following the tasks in order. Do not change the architecture, API contracts, \
             UI screens, or stack. Stop and ask only if a task's acceptance criteria \
             cannot be met given the supplied PRD.\n\n",
        );
        s.push_str("## Original Request\n\n");
        s.push_str(&format!("> {}\n\n", p.user_request));
        s.push_str("## Stack\n\n");
        s.push_str(&format!(
            "- Language: {}\n- Frameworks: {}\n- Storage: {}\n- Runtime target: {}\n\n",
            p.stack.language,
            p.stack.frameworks.join(", "),
            p.stack.storage,
            p.stack.runtime_target
        ));
        s.push_str("## Architecture Overview\n\n");
        s.push_str(&format!("{}\n\n", p.architecture.overview));

        if !p.api.endpoints.is_empty() {
            s.push_str("## API Contract (must implement exactly)\n\n");
            for e in &p.api.endpoints {
                s.push_str(&format!("- `{} {}` — {}\n", e.method.as_str(), e.path, e.summary));
            }
            s.push('\n');
        }
        if !p.ui.screens.is_empty() {
            s.push_str("## UI Screens (must implement exactly)\n\n");
            for sc in &p.ui.screens {
                s.push_str(&format!("- `{}` at `{}` — {}\n", sc.id, sc.route, sc.purpose));
            }
            s.push('\n');
        }

        s.push_str("## Tasks (execute in order)\n\n");
        let mut tasks = p.tasks.clone();
        tasks.sort_by_key(|t| t.order);
        for t in &tasks {
            s.push_str(&format!("### {}. {} (`{}`)\n\n", t.order, t.goal, t.id));
            if !t.files_touched.is_empty() {
                s.push_str(&format!("- Files: {}\n", t.files_touched.join(", ")));
            }
            if !t.acceptance_criteria.is_empty() {
                s.push_str("- Acceptance:\n");
                for ac in &t.acceptance_criteria {
                    s.push_str(&format!("  - {ac}\n"));
                }
            }
            if !t.depends_on.is_empty() {
                s.push_str(&format!("- Depends on: {}\n", t.depends_on.join(", ")));
            }
            s.push('\n');
        }

        if !p.risks.is_empty() {
            s.push_str("## Known Risks (mitigate as you go)\n\n");
            for r in &p.risks {
                s.push_str(&format!("- {} — mitigation: {}\n", r.description, r.mitigation));
            }
        }
        s
    }
}

fn fields_table(fields: &[ApiField]) -> String {
    let mut s = String::from("| Name | Type | Required | Description |\n|---|---|---|---|\n");
    for f in fields {
        s.push_str(&format!(
            "| `{}` | `{}` | {} | {} |\n",
            f.name, f.ty, f.required, f.description
        ));
    }
    s
}

fn body_md(label: &str, body: &ApiBody) -> String {
    let mut s = format!("**{label}** (`{}`)\n\n", body.content_type);
    if !body.fields.is_empty() {
        s.push_str(&fields_table(&body.fields));
        s.push('\n');
    }
    if let Some(ex) = &body.example {
        s.push_str("Example:\n\n```\n");
        s.push_str(ex);
        s.push_str("\n```\n\n");
    }
    s
}

fn screen_md(sc: &UiScreen) -> String {
    let mut s = format!("### `{}` — {} (`{}`)\n\n", sc.id, sc.name, sc.route);
    s.push_str(&format!("**Purpose**: {}\n\n", sc.purpose));
    if !sc.user_flow.is_empty() {
        s.push_str("**User flow**:\n\n");
        for (i, step) in sc.user_flow.iter().enumerate() {
            s.push_str(&format!("{}. {}\n", i + 1, step));
        }
        s.push('\n');
    }
    if !sc.component_refs.is_empty() {
        s.push_str(&format!("**Components used**: {}\n\n", sc.component_refs.join(", ")));
    }
    if !sc.api_endpoint_refs.is_empty() {
        s.push_str(&format!("**API endpoints**: {}\n\n", sc.api_endpoint_refs.join(", ")));
    }
    if !sc.entity_refs.is_empty() {
        s.push_str(&format!("**Entities**: {}\n\n", sc.entity_refs.join(", ")));
    }
    s
}

fn rule_md(r: &BusinessRule) -> String {
    let mut s = format!("- **`{}` — {}** *({:?})*: {}\n", r.id, r.name, r.severity, r.description);
    if !r.entity_refs.is_empty() {
        s.push_str(&format!("  - Entities: {}\n", r.entity_refs.join(", ")));
    }
    if !r.triggered_by.is_empty() {
        s.push_str(&format!("  - Triggered by: {}\n", r.triggered_by.join(", ")));
    }
    s
}

fn workflow_md(w: &Workflow) -> String {
    let mut s = format!("#### `{}` — {}\n\n", w.id, w.name);
    s.push_str(&format!("**Trigger**: {}\n\n", w.trigger));
    s.push_str("| # | Actor | Action | System response |\n|---|---|---|---|\n");
    let mut steps = w.steps.clone();
    steps.sort_by_key(|st| st.order);
    for st in &steps {
        s.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            st.order, st.actor, st.action, st.system_response
        ));
    }
    if !w.rule_refs.is_empty() {
        s.push_str(&format!("\n**Rules applied**: {}\n", w.rule_refs.join(", ")));
    }
    s.push('\n');
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::api_spec::{ApiEndpoint, ApiResponseStatus, HttpMethod};
    use crate::plan::{Component, Plan};
    use crate::task::{Complexity, Task};
    use crate::ui_spec::UiScreen;

    fn make_plan() -> Plan {
        let mut p = Plan::new("track deliveries");
        p.problem.summary = "Test".into();
        p.architecture.overview = "ov".into();
        p.architecture.mermaid_diagram = "graph TD; A-->B".into();
        p.architecture.components.push(Component {
            id: "c1".into(),
            name: "n".into(),
            responsibility: "r".into(),
            depends_on: vec![],
        });
        p.stack.language = "Rust".into();
        p.api.base_url = "http://localhost:8080".into();
        p.api.endpoints.push(ApiEndpoint {
            id: "e1".into(),
            method: HttpMethod::Post,
            path: "/deliveries".into(),
            summary: "create".into(),
            auth_required: false,
            query_params: vec![],
            path_params: vec![],
            request_body: None,
            response_body: None,
            statuses: vec![ApiResponseStatus { code: 201, description: "created".into() }],
            entity_refs: vec![],
            component_refs: vec!["c1".into()],
        });
        p.ui.framework = "React".into();
        p.ui.screens.push(UiScreen {
            id: "s1".into(),
            name: "Entry".into(),
            route: "/entry".into(),
            purpose: "log delivery".into(),
            component_refs: vec![],
            user_flow: vec!["open".into(), "submit".into()],
            api_endpoint_refs: vec!["e1".into()],
            entity_refs: vec![],
        });
        p.tasks.push(Task {
            id: "t1".into(),
            order: 1,
            goal: "g".into(),
            component_refs: vec!["c1".into()],
            inputs: vec![],
            outputs: vec![],
            files_touched: vec!["src/main.rs".into()],
            acceptance_criteria: vec!["compiles".into()],
            complexity: Complexity::S,
            depends_on: vec![],
        });
        p
    }

    #[test]
    fn writes_all_required_documents() {
        let tmp = std::env::temp_dir().join(format!("godsy-test-{}", uuid::Uuid::new_v4()));
        fs::create_dir_all(&tmp).unwrap();
        let dir = PlanBundleWriter::new(&make_plan()).write_to(&tmp).unwrap();
        for f in [
            "PRD.md",
            "API.md",
            "UI.md",
            "CODING_AGENT_PROMPT.md",
            "risks.md",
            "tasks.json",
            "confidence.json",
            "plan.json",
            "audit.log",
        ] {
            assert!(dir.join(f).exists(), "missing {f}");
        }
        let api = fs::read_to_string(dir.join("API.md")).unwrap();
        assert!(api.contains("POST"));
        assert!(api.contains("/deliveries"));
        let ui = fs::read_to_string(dir.join("UI.md")).unwrap();
        assert!(ui.contains("Entry"));
        assert!(ui.contains("/entry"));
        let prd = fs::read_to_string(dir.join("PRD.md")).unwrap();
        assert!(prd.contains("Execution Plan"));
        assert!(prd.contains("Architecture Overview"));
        fs::remove_dir_all(&tmp).ok();
    }
}
